### ISSUE TITLE
DistributionNotFound: dbgp==1.1

### ISSUE THREAD

**Issue by alfonsodev** [jaredly/pydbgp#1]
Im working on Mac Os 10.8 with python 2.7
I've cloned the project, then 

```
cd pydbgp
python setup.py install -v
```

installation worked
now I tried to start debugging but I get the following error
can you put an example in README file ? thanks!

```
$ python -S /usr/local/bin/pydbgp.py -d localhost:9000 po2csv.py 
Traceback (most recent call last):
  File "/usr/local/bin/pydbgp.py", line 4, in <module>
    import pkg_resources
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/../../Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/../../Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/../../Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: dbgp==1.1
```

**Comment by alfonsodev** [comment]
This is all the output from setup script

```
$ sudo python setup.py install -v
Password:
running install
running bdist_egg
running egg_info
creating dbgp.egg-info
writing dbgp.egg-info/PKG-INFO
writing top-level names to dbgp.egg-info/top_level.txt
writing dependency_links to dbgp.egg-info/dependency_links.txt
writing manifest file 'dbgp.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'dbgp/_client??.c'
writing manifest file 'dbgp.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.8-intel/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/dbgp
copying dbgp/__init__.py -> build/lib/dbgp
copying dbgp/_pyclient.py -> build/lib/dbgp
copying dbgp/client.py -> build/lib/dbgp
copying dbgp/common.py -> build/lib/dbgp
copying dbgp/listcmd.py -> build/lib/dbgp
copying dbgp/server.py -> build/lib/dbgp
copying dbgp/serverBase.py -> build/lib/dbgp
creating build/bdist.macosx-10.8-intel
creating build/bdist.macosx-10.8-intel/egg
creating build/bdist.macosx-10.8-intel/egg/dbgp
copying build/lib/dbgp/__init__.py -> build/bdist.macosx-10.8-intel/egg/dbgp
copying build/lib/dbgp/_pyclient.py -> build/bdist.macosx-10.8-intel/egg/dbgp
copying build/lib/dbgp/client.py -> build/bdist.macosx-10.8-intel/egg/dbgp
copying build/lib/dbgp/common.py -> build/bdist.macosx-10.8-intel/egg/dbgp
copying build/lib/dbgp/listcmd.py -> build/bdist.macosx-10.8-intel/egg/dbgp
copying build/lib/dbgp/server.py -> build/bdist.macosx-10.8-intel/egg/dbgp
copying build/lib/dbgp/serverBase.py -> build/bdist.macosx-10.8-intel/egg/dbgp
byte-compiling build/bdist.macosx-10.8-intel/egg/dbgp/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.8-intel/egg/dbgp/_pyclient.py to _pyclient.pyc
byte-compiling build/bdist.macosx-10.8-intel/egg/dbgp/client.py to client.pyc
byte-compiling build/bdist.macosx-10.8-intel/egg/dbgp/common.py to common.pyc
byte-compiling build/bdist.macosx-10.8-intel/egg/dbgp/listcmd.py to listcmd.pyc
byte-compiling build/bdist.macosx-10.8-intel/egg/dbgp/server.py to server.pyc
byte-compiling build/bdist.macosx-10.8-intel/egg/dbgp/serverBase.py to serverBase.pyc
creating build/bdist.macosx-10.8-intel/egg/EGG-INFO
installing scripts to build/bdist.macosx-10.8-intel/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-2.7
copying and adjusting bin/pydbgp.py -> build/scripts-2.7
copying and adjusting bin/pydbgpproxy.py -> build/scripts-2.7
changing mode of build/scripts-2.7/pydbgp.py from 644 to 755
changing mode of build/scripts-2.7/pydbgpproxy.py from 644 to 755
creating build/bdist.macosx-10.8-intel/egg/EGG-INFO/scripts
copying build/scripts-2.7/pydbgp.py -> build/bdist.macosx-10.8-intel/egg/EGG-INFO/scripts
copying build/scripts-2.7/pydbgpproxy.py -> build/bdist.macosx-10.8-intel/egg/EGG-INFO/scripts
changing mode of build/bdist.macosx-10.8-intel/egg/EGG-INFO/scripts/pydbgp.py to 755
changing mode of build/bdist.macosx-10.8-intel/egg/EGG-INFO/scripts/pydbgpproxy.py to 755
copying dbgp.egg-info/PKG-INFO -> build/bdist.macosx-10.8-intel/egg/EGG-INFO
copying dbgp.egg-info/SOURCES.txt -> build/bdist.macosx-10.8-intel/egg/EGG-INFO
copying dbgp.egg-info/dependency_links.txt -> build/bdist.macosx-10.8-intel/egg/EGG-INFO
copying dbgp.egg-info/top_level.txt -> build/bdist.macosx-10.8-intel/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
dbgp.client: module references __file__
dbgp.client: module references __path__
creating dist
creating 'dist/dbgp-1.1-py2.7.egg' and adding 'build/bdist.macosx-10.8-intel/egg' to it
removing 'build/bdist.macosx-10.8-intel/egg' (and everything under it)
Processing dbgp-1.1-py2.7.egg
creating /Library/Python/2.7/site-packages/dbgp-1.1-py2.7.egg
Extracting dbgp-1.1-py2.7.egg to /Library/Python/2.7/site-packages
Adding dbgp 1.1 to easy-install.pth file
Installing pydbgp.py script to /usr/local/bin

```

**Comment by alfonsodev** [comment]
also I've checked and dbgp 1.1 is installed 

```
$ sudo easy_install dbgp
Searching for dbgp
Best match: dbgp 1.1
Processing dbgp-1.1-py2.7.egg
dbgp 1.1 is already the active version in easy-install.pth
Installing pydbgp.py script to /usr/local/bin
Installing pydbgpproxy.py script to /usr/local/bin

Using /Library/Python/2.7/site-packages/dbgp-1.1-py2.7.egg
Processing dependencies for dbgp
Finished processing dependencies for dbgp
```

**Comment by jaredly** [comment]
Hmmm I've never tried to install it on a mac. Does activestate's original package work?

**Comment by alfonsodev** [comment]
activestate's fails in the same way, seems like it's my environment. I close it.
Thanks for quick response.
